CONFIG_WIFI_NRF71=y
CONFIG_NRF71_SOFT_HPQM=y
CONFIG_NRF71_CMD_RX_BUFF=y
CONFIG_NRF_WIFI_LOW_POWER=n
CONFIG_WIFI_FIXED_MAC_ADDRESS="00:11:22:33:39:79"
CONFIG_WIFI_FIXED_MAC_ADDRESS_ENABLED=y
#CONFIG_RAW_TX_PKT_SAMPLE_CHANNEL=6
CONFIG_NRF70_TCP_IP_CHECKSUM_OFFLOAD=n
CONFIG_NRF_WIFI_MGMT_BUFF_OFFLOAD=n
CONFIG_LOG_MODE_IMMEDIATE=y
